export default {
  products: [
    {
      name: 'Produto 1',
      price: 10.99,
      category: 'Categoria 1',
      stock: 5,
      maxStock: 20,
      minStock: 2,
    },
    {
      name: 'Produto 2',
      price: 20.99,
      category: 'Categoria 2',
      stock: 10,
      maxStock: 30,
      minStock: 5,
    },
    {
      name: 'Produto 3',
      price: 30.99,
      category: 'Categoria 3',
      stock: 15,
      maxStock: 40,
      minStock: 8,
    },
    {
      name: 'Produto 4',
      price: 40.99,
      category: 'Categoria 4',
      stock: 20,
      maxStock: 50,
      minStock: 10,
    },
    {
      name: 'Produto 5',
      price: 50.99,
      category: 'Categoria 5',
      stock: 25,
      maxStock: 60,
      minStock: 12,
    },
    {
      name: 'Produto 6',
      price: 60.99,
      category: 'Categoria 6',
      stock: 30,
      maxStock: 70,
      minStock: 15,
    },
    {
      name: 'Produto 7',
      price: 70.99,
      category: 'Categoria 7',
      stock: 35,
      maxStock: 80,
      minStock: 18,
    },
    {
      name: 'Produto 8',
      price: 80.99,
      category: 'Categoria 8',
      stock: 40,
      maxStock: 90,
      minStock: 20,
    },
    {
      name: 'Produto9',
      price: 90.99,
      category: 'Categoria9',
      stock: 45,
      maxStock: 100,
      minStock: 22,
    },
    {
      name: 'Produto10',
      price: 100.99,
      category: 'Categoria10',
      stock: 50,
      maxStock: 110,
      minStock: 25,
    },
    {
      name: 'Produto11',
      price: 110.99,
      category: 'Categoria11',
      stock: 55,
      maxStock: 120,
      minStock: 28,
    },
    {
      name: 'Produto12',
      price: 120.99,
      category: 'Categoria12',
      stock: 60,
      maxStock: 130,
      minStock: 30,
    },
    {
      name: 'Produto13',
      price: 130.99,
      category: 'Categoria13',
      stock: 14,
      maxStock: 140,
      minStock: 32,
    },
    {
      name: 'Produto14',
      price: 140.99,
      category: 'Categoria14',
      stock: 0,
      maxStock: 150,
      minStock: 35,
    },
    {
      name: 'Produto15',
      price: 150.99,
      category: 'Categoria15',
      stock: 75,
      maxStock: 160,
      minStock: 38,
    },
  ],
}
